use_frameworks!

platform :ios, '10.0'

target 'uds-ios-theme-public-mobile_Example' do
  pod 'uds-ios-theme-public-mobile', :path => '../'

  target 'uds-ios-theme-public-mobile_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
